services:
  npm2pihole:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
        # Path to Nginx Proxy Manager's data/nginx/proxy_host folder.
      - /path/to/npm/data/nginx/proxy_host/:/app/npm/:ro
        # SSH key(s) for remote Pi-hole access
      - ./ssh/:/root/.ssh/
