services:
  npm2pihole:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      # Docker socket for restarting NPM container
      - /var/run/docker.sock:/var/run/docker.sock
      # Path to Nginx Proxy Manager's config directory (read-write to generate configs)
      - /Users/rjames/Documents/dockge/stacks/npm/npm/data/nginx/proxy_host/:/app/npm-configs/
      # SSH key(s) for remote Pi-hole access
      - ./ssh/:/root/.ssh/

networks: {}
