services:
  npm2pihole:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      # Docker socket for NPM API calls
      - /var/run/docker.sock:/var/run/docker.sock
      # Services configuration file (editable without rebuilds)
      - ./data/:/app/data/
      # SSH key(s) for remote Pi-hole access
      - ./ssh/:/root/.ssh/

networks: {}
